{
    'name': 'VIT Demo POS',
    'version': '17.0.1.0.0',
    'category': 'Point of Sale',
    'summary': """Belong to VIT""",
    'author': 'Visi Intech',
    'company': 'Visi Intech',
    'maintainer': 'Visi Intech',
    'website': "https://www.Visi-Intech.com",
    'depends': ['point_of_sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/views_card_number.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'dev_pos/static/src/css/pop_up.css',
            'dev_pos/static/src/xml/button.xml',
            # 'dev_pos/static/src/xml/button_screen.xml',
            'dev_pos/static/src/js/button.js',
            'dev_pos/static/src/js/pop_up_card.js',
            'dev_pos/static/src/js/PaymentScreen.js',
        ],
    },
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}