name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - development  # atau branch lain yang Anda inginkan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SSH
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -p 21787" --exclude '.git*' ./ root@116.254.101.213:/vit/odoo/odoo17/addons_new

    - name: Restart Odoo Service
      run: |
        echo "${{ secrets.SSH_PASSWORD }}" | ssh -o StrictHostKeyChecking=no -p 21787 root@116.254.101.213 'sudo -S systemctl restart odoo17dev.service'